import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/*header*/}
      <Navbar/>
      <main>
        {/*sidebar*/}
        {/*newsfeed*/}
        {/*contacts*/}
      </main>
    </div>
  )
}
